### ISSUE TITLE
Hanging when posting Tasks to Todoist

### ISSUE THREAD

**Issue by hasii2011** [hasii2011/gittodoistclone#14]
I am on Big Sur 11.4;

Might have to update my GitHub and/or Todoist dependencies

**Comment by hasii2011** [comment]
09:56:25.323 WARNING TodoistAdapter: No items means this is a new project
Traceback (most recent call last):
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/gittodoistclone/gittodoistclone/ui/TodoistPanel.py", line 125, in _onCreateTaskClicked
    adapter.createTasks(info=ci, progressCb=self.__adapterCallback)
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/gittodoistclone/gittodoistclone/adapters/TodoistAdapter.py", line 75, in createTasks
    self._todoist.commit()
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/gittodoistclone/pyenv-venv-3.9.1/lib/python3.9/site-packages/todoist/api.py", line 382, in commit
    raise SyncError(k, v)
todoist.api.SyncError: ('865a978a-cc57-11eb-a003-acde48001122', {'error': 'Invalid temporary id', 'error_code': 16, 'error_extra': {}, 'error_tag': 'INVALID_TEMPID', 'http_code': 400})

Process finished with exit code 0

**Comment by hasii2011** [comment]
The above is related to reaching a Todoist limit.  After this fails the first time then the Todoist cache is corrupted with and invalid temporary id.  The only way I know to get rid of this I found on the Todoist user from was to delete ${HOME}/.todoist.sync

**Comment by hasii2011** [comment]
Fixed
